import type { UserProfile, RoadmapPathway, ParentBrief, ChatMessage } from '../types/career';
import { MOCK_ROADMAPS_HIGH_SCHOOL, MOCK_PARENT_BRIEFS } from '../data/mockRoadmaps';

const API_KEY_STORAGE_KEY = 'CAREERFORGE_GEMINI_KEY';

export const getStoredApiKey = (): string => {
  return localStorage.getItem(API_KEY_STORAGE_KEY) || import.meta.env.VITE_GEMINI_API_KEY || '';
};

export const setStoredApiKey = (key: string): void => {
  if (key.trim()) {
    localStorage.setItem(API_KEY_STORAGE_KEY, key.trim());
  } else {
    localStorage.removeItem(API_KEY_STORAGE_KEY);
  }
};

/**
 * Call Gemini REST API directly using standard fetch for zero-dependency browser compatibility
 */
async function callGeminiApi(prompt: string, apiKey: string): Promise<string> {
  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;

  const response = await fetch(endpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      contents: [{
        parts: [{ text: prompt }]
      }],
      generationConfig: {
        temperature: 0.7,
        maxOutputTokens: 3500,
      }
    })
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(errorData.error?.message || `Gemini API Error: HTTP ${response.status}`);
  }

  const data = await response.json();
  const textOutput = data.candidates?.[0]?.content?.parts?.[0]?.text;
  if (!textOutput) {
    throw new Error("No content generated by Gemini API.");
  }
  return textOutput;
}

/**
 * Clean Markdown backticks and extra text surrounding JSON response
 */
function parseJsonResponse<T>(text: string): T {
  let cleaned = text.trim();
  if (cleaned.startsWith('```json')) {
    cleaned = cleaned.replace(/^```json\s*/, '').replace(/\s*```$/, '');
  } else if (cleaned.startsWith('```')) {
    cleaned = cleaned.replace(/^```\s*/, '').replace(/\s*```$/, '');
  }
  return JSON.parse(cleaned) as T;
}

/**
 * Generate 3 Distinct Roadmaps based on user profile
 */
export async function generateCareerRoadmaps(userProfile: UserProfile): Promise<{ roadmaps: RoadmapPathway[]; isLiveAI: boolean }> {
  const apiKey = getStoredApiKey();

  if (!apiKey) {
    console.log("No Gemini API key provided. Using fallback demo roadmaps.");
    return { roadmaps: MOCK_ROADMAPS_HIGH_SCHOOL, isLiveAI: false };
  }

  const systemPrompt = `
You are an expert AI Career Strategist for CAREERFORGE.
Given the following student/professional profile:
- Career Stage: ${userProfile.stage} (e.g. high_school, college, professional, switcher)
- Stream / Background: ${userProfile.streamOrField}
- Current Level / Grade: ${userProfile.gradeOrYear}
- Core Skills: ${userProfile.skills.join(', ')}
- Interests: ${userProfile.interests.join(', ')}
- Preferred Work Style: ${userProfile.workStyle}
- Budget & Timeline: ${userProfile.budgetTimeline}

TASK:
Generate EXACTLY 3 DISTINCT career pathways tailored specifically to this user:
1. Path A (type: "traditional"): University/Higher Education / Accredited Deep Dive Pathway.
2. Path B (type: "tech_skill_first"): High-Growth Skill-First Fast-Track / Bootcamp / Industry Certifications Pathway.
3. Path C (type: "niche_emerging"): Niche, Interdisciplinary, or Emerging Frontier Pathway.

Return ONLY a valid JSON array of 3 objects conforming to this TypeScript structure:
[
  {
    "id": "path-1",
    "title": "Clear Actionable Title",
    "type": "traditional" | "tech_skill_first" | "niche_emerging",
    "subtitle": "Short 1-line tag",
    "matchPercentage": 95,
    "overview": "Detailed summary of this path",
    "suitabilityReason": "Why this path matches their specific profile",
    "entryLevelSalary": "Estimated entry salary range in INR & USD",
    "midCareerSalary": "Estimated 5-year salary range in INR & USD",
    "growthOutlook": "Industry growth metrics (e.g., +28% growth)",
    "stabilityScore": 9,
    "steps": [
      {
        "id": "step-1",
        "phaseTitle": "Phase 1: Title",
        "timeframe": "Timeframe",
        "description": "Overview of phase",
        "keyMilestones": ["Milestone 1", "Milestone 2"],
        "skillsToAcquire": [
          { "name": "Skill Name", "difficulty": "Beginner" | "Intermediate" | "Advanced" }
        ],
        "entranceExamsOrCerts": [
          { "name": "JEE / AWS / Cert Name", "type": "Exam" | "Cert" | "Degree" | "Portfolio", "details": "Brief info" }
        ],
        "recommendedDegreesOrCourses": ["Degree or Course Name"],
        "learningResources": [
          { "title": "Resource Name", "type": "Free Course" | "Certification" | "Platform", "url": "https://..." }
        ]
      }
    ]
  }
]
IMPORTANT: Return strictly raw JSON. Do NOT wrap in markdown explanation text.
`;

  try {
    const rawResult = await callGeminiApi(systemPrompt, apiKey);
    const roadmaps = parseJsonResponse<RoadmapPathway[]>(rawResult);
    return { roadmaps, isLiveAI: true };
  } catch (err) {
    console.error("Gemini API generation failed, using fallback roadmaps:", err);
    return { roadmaps: MOCK_ROADMAPS_HIGH_SCHOOL, isLiveAI: false };
  }
}

/**
 * Generate 1-Page Parent Brief / Stakeholder Summary for a specific pathway
 */
export async function generateParentBrief(userProfile: UserProfile, pathway: RoadmapPathway): Promise<ParentBrief> {
  const apiKey = getStoredApiKey();

  // If no API key or cached fallback
  if (!apiKey || MOCK_PARENT_BRIEFS[pathway.id]) {
    return MOCK_PARENT_BRIEFS[pathway.id] || {
      pathwayId: pathway.id,
      pathwayTitle: pathway.title,
      targetAudience: userProfile.stage === 'high_school' || userProfile.stage === 'college' ? 'Parent' : 'Stakeholder',
      executiveSummary: `This executive brief outlines the strategic value, financial return, and industry stability of the ${pathway.title} pathway.`,
      whyThisCareer: pathway.overview,
      industryStabilityGrowth: pathway.growthOutlook,
      financialROI: `Entry-level salary starts around ${pathway.entryLevelSalary}, growing to ${pathway.midCareerSalary} within 5 years.`,
      formalDegreeBacking: `Backed by accredited computer science/engineering degrees and industry-recognized professional certifications.`,
      parentActionPlan: [
        'Support target skill development and exam/cert registrations.',
        'Ensure access to computer equipment and high-speed internet.',
        'Encourage networking and project building.'
      ],
      automationRiskRating: 'Low'
    };
  }

  const systemPrompt = `
You are an executive career advisor.
Generate a reassuring, highly structured 1-page "Parent / Stakeholder Brief" for a student/professional pursuing the career pathway: "${pathway.title}".

User Profile: Stage: ${userProfile.stage}, Stream: ${userProfile.streamOrField}.
Pathway Details:
- Title: ${pathway.title}
- Overview: ${pathway.overview}
- Entry Salary: ${pathway.entryLevelSalary}
- Mid Career Salary: ${pathway.midCareerSalary}
- Growth Outlook: ${pathway.growthOutlook}

Generate a JSON object matching this TypeScript structure:
{
  "pathwayId": "${pathway.id}",
  "pathwayTitle": "${pathway.title}",
  "targetAudience": "${userProfile.stage === 'high_school' || userProfile.stage === 'college' ? 'Parent' : 'Stakeholder'}",
  "executiveSummary": "A clear 2-3 sentence overview explaining why this is a high-opportunity choice.",
  "whyThisCareer": "Explanation in simple, non-jargon language of what the job involves and its real-world impact.",
  "industryStabilityGrowth": "Detailed breakdown of 5-10 year market demand and economic stability.",
  "financialROI": "Financial return on investment analysis (starting salary vs growth).",
  "formalDegreeBacking": "Details on official university degrees, entrance exams, or accredited certifications backing this path.",
  "parentActionPlan": [
    "Actionable bullet point 1",
    "Actionable bullet point 2",
    "Actionable bullet point 3"
  ],
  "automationRiskRating": "Very Low" | "Low" | "Moderate"
}

Return strictly raw JSON.
`;

  try {
    const rawResult = await callGeminiApi(systemPrompt, apiKey);
    return parseJsonResponse<ParentBrief>(rawResult);
  } catch (err) {
    console.error("Gemini Parent Brief generation failed, returning fallback:", err);
    return {
      pathwayId: pathway.id,
      pathwayTitle: pathway.title,
      targetAudience: 'Parent',
      executiveSummary: `This executive brief outlines the strategic value and ROI of the ${pathway.title} pathway.`,
      whyThisCareer: pathway.overview,
      industryStabilityGrowth: pathway.growthOutlook,
      financialROI: `Entry-level salary starting at ${pathway.entryLevelSalary}.`,
      formalDegreeBacking: `Backed by accredited university courses and certifications.`,
      parentActionPlan: [
        'Encourage foundation math and coding practice.',
        'Support entrance exam registrations.',
        'Provide a dedicated study environment.'
      ],
      automationRiskRating: 'Low'
    };
  }
}

/**
 * AI Mentor Chat Assistant
 */
export async function sendMentorChatMessage(
  messages: ChatMessage[],
  currentRoadmap: RoadmapPathway | null,
  userProfile: UserProfile
): Promise<string> {
  const apiKey = getStoredApiKey();

  if (!apiKey) {
    const lastUserMsg = messages[messages.length - 1]?.text.toLowerCase() || '';
    if (lastUserMsg.includes('parent') || lastUserMsg.includes('explain')) {
      return "To explain this career to your parents, highlight the 5-10 year stability (+30% market growth), official degree options (B.Tech / B.Sc), and strong entry-level salary potential. You can also click 'Generate Parent Brief' above for a ready-to-print 1-page summary!";
    }
    if (lastUserMsg.includes('exam') || lastUserMsg.includes('jee') || lastUserMsg.includes('cuet')) {
      return "For entrance exam prep alongside your current schedule, dedicate 3 hours daily to core Math/Physics concepts, solve previous 5-year question papers, and take weekly mock tests on weekends.";
    }
    return `As your AI Career Mentor, I recommend focusing on building practical projects alongside your ${userProfile.streamOrField} studies. Is there a specific milestone in ${currentRoadmap ? currentRoadmap.title : 'your roadmap'} you would like to explore deeper?`;
  }

  const roadmapContext = currentRoadmap ? `Current Selected Roadmap: ${currentRoadmap.title}\nOverview: ${currentRoadmap.overview}\nMilestones: ${currentRoadmap.steps.map(s => s.phaseTitle).join(', ')}` : 'No specific roadmap selected yet.';

  const prompt = `
You are CAREERFORGE AI Mentor, an empathetic, expert career counselor for high schoolers, college students, and working professionals.
User Profile: Stage: ${userProfile.stage}, Stream: ${userProfile.streamOrField}.
${roadmapContext}

Chat History:
${messages.map(m => `${m.sender.toUpperCase()}: ${m.text}`).join('\n')}

Respond to the latest user message with clear, actionable, encouraging advice. Keep responses concise (2-4 paragraphs max). Use bullet points where appropriate.
`;

  try {
    return await callGeminiApi(prompt, apiKey);
  } catch (err) {
    return "I'm experiencing a brief connectivity hiccup with the AI server. However, based on your roadmap, focusing on your core milestone skills and entrance exams is your best next step!";
  }
}
